application:
  allowed-extensions: ""
  file-directory: ""
  version: 1.0

server:
  port: 8081

spring:
  application:
    name: File-Server
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB